name: spajam2022
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cloud_firestore:
  cloud_functions:
  cupertino_icons:
  firebase_analytics:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  firebase_dynamic_links:
  firebase_messaging:
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_hooks:
  package_info_plus: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
  flutter_native_splash:

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/splash_icons/splash_light.png'
  color_dark: '#000000'
  image_dark: 'assets/splash_icons/splash_dark.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/splash_icons/splash_light.png'
    icon_background_color_dark: '#000000'
    image_dark: 'assets/splash_icons/splash_dark.png'
