name: spajam2022
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cached_network_image:
  cloud_firestore:
  cloud_functions:
  connectivity_plus:
  cookie_jar:
  cupertino_icons:
  dio:
  dio_cookie_manager:
  firebase_analytics:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  firebase_dynamic_links:
  firebase_messaging:
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_datetime_picker_bdaya:
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  flutter_spinkit:
  font_awesome_flutter:
  freezed_annotation:
  gap:
  hooks_riverpod:
  intl:
  package_info_plus: ^1.4.3
  path_provider:
  path_to_regexp:
  shimmer:
  simple_logger:
  tuple:
  uuid:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints: ^2.0.0
  flutter_native_splash:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable: ^6.3.1
  pedantic_mono:

dependency_overrides:
  hooks_riverpod: '>=2.0.0-0'

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/splash_icons/splash_light.png'
  color_dark: '#000000'
  image_dark: 'assets/splash_icons/splash_dark.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/splash_icons/splash_light.png'
    icon_background_color_dark: '#000000'
    image_dark: 'assets/splash_icons/splash_dark.png'
